@HOST = http://localhost:3000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3ZDNkODBlMi1iYzFjLTRlZTQtOGI5Zi1jMmJiYTA1MThmYmYiLCJuYW1lIjoiYmFsZXhhbmRyZSIsImJpcnRoIjoiMjAyMC0wNS0wMVQxOTo1Njo0MC41MjVaIiwiaWF0IjoxNTg4MzYzMDAwLCJleHAiOjE1ODgzNjM2MDAsImlzcyI6Imh0dHBzOi8vYXV0aC5oZWFwLmRrL2NoYWxsZW5nZSJ9.PSrZPWRaJAC9VBegD8Bq4zruVwYi6yJBPd6DQ9vliDQ

### get token
POST {{HOST}}/login
Content-Type: application/json

{
    "username": "balexandre",
    "password": "pa55w0rd"
}

### show the saved object
GET {{HOST}}/object
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### save the object with error
POST {{HOST}}/object
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "id": "779b8611f717494cb230abac00a8f40a",
  "name": "Heap",
  "birth": "2020-01-01T10:10:10Z",
  "products": []
}

### save the object
POST {{HOST}}/object
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "id": "779b8611f717494cb230abac00a8f40a",
  "name": "Heap",
  "birth": "2020-01-01T10:10:10Z",
  "products": [
    {
      "id": 1,
      "name": "Product 1",
      "price": 200
    },
    {
      "id": 2,
      "name": "Product 2",
      "price": 400
    }
  ]
}
