@HOST = http://localhost:3000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3ZDNkODBlMi1iYzFjLTRlZTQtOGI5Zi1jMmJiYTA1MThmYmYiLCJuYW1lIjoiYmFsZXhhbmRyZSIsImJpcnRoIjoiMjAyMC0wNS0wMVQxOTo1Njo0MC41MjVaIiwiaWF0IjoxNTg4MzYzMDAwLCJleHAiOjE1ODgzNjM2MDAsImlzcyI6Imh0dHBzOi8vYXV0aC5oZWFwLmRrL2NoYWxsZW5nZSJ9.PSrZPWRaJAC9VBegD8Bq4zruVwYi6yJBPd6DQ9vliDQ

### should throw 404 as route does not exists
GET {{HOST}}

### get token
POST {{HOST}}/login
Content-Type: application/json

{
    "username": "balexandre",
    "password": "pa55w0rd"
}

### access public route (accessible from everyone)
GET {{HOST}}/public
Content-Type: application/json

### access secret route (accessible from a valid token)
# using manual middleware
GET {{HOST}}/secret1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### access secret route (accessible from a valid token)
# using express-jwt middleware
GET {{HOST}}/secret2
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
